//	/*
// 	*
// 	* Copyright (C) 2003-2010 Alexandros Economou
//	*
//	* This file is part of Jaangle (http://www.jaangle.com)
// 	*
// 	* This Program is free software; you can redistribute it and/or modify
// 	* it under the terms of the GNU General Public License as published by
// 	* the Free Software Foundation; either version 2, or (at your option)
// 	* any later version.
// 	*
// 	* This Program is distributed in the hope that it will be useful,
// 	* but WITHOUT ANY WARRANTY; without even the implied warranty of
// 	* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// 	* GNU General Public License for more details.
// 	*
// 	* You should have received a copy of the GNU General Public License
// 	* along with GNU Make; see the file COPYING. If not, write to
// 	* the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
// 	* http://www.gnu.org/copyleft/gpl.html
// 	*
//	*/ 
#define IDOK2                           3
#define IDC_RETRY                       3
#define IDC_RESCAN                      3
#define IDOK3                           4
#define IDM_ABOUTBOX                    0x0010
#define IDR_MAINFRAME                   50
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TEENSPIRIT_DIALOG           102
#define IDS_EXPORTSELECTEDLINES         102
#define IDS_ALBUM                       103
#define IDD_PPLATESTADDITIONS           104
#define IDS_EXPORTALL                   104
#define IDS_TRACKNO                     105
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_PPSIMPLESEARCH              106
#define IDS_LOCATION                    106
#define IDS_SIZE                        107
#define IDS_TYPE                        108
#define IDS_DURATION                    109
#define IDS_BITRATE                     110
#define IDS_DELETEFROMHISTORY           111
#define IDS_GENRE                       112
#define IDS_COMMENT                     113
#define IDS_LOCATION2                   113
#define IDS_DATEADDED                   114
#define IDS_ADDED                       114
#define IDS_RATING                      115
#define IDS_TRACKNOTFOUND               116
#define IDS_NUMBEROFTRACKS              117
#define IDS_DATEUPDATED                 119
#define IDS_UPDATED                     119
#define IDS_OPERATION                   120
#define IDS_NOITEMS                     121
#define IDS_STATUS_MAIN                 123
#define IDS_STATUS_INFO                 124
#define IDS_TOTALSIZEOFTRACKS           125
#define ID_SEARCH_STAT_MSG              126
#define IDS_IDLE                        126
#define ID_SEARCH_STAT_RECORDS          127
#define IDS_RECORDS                     127
#define ID_SEARCH_STAT_TIME             128
#define IDS_SHOWYEAR                    128
#define IDR_MAINMENU                    129
#define IDS_FIRSTAPPEARANCE             129
#define IDR_MAIN_TOOLBAR                130
#define IDS_LASTAPPEARANCE              130
#define IDS_RANK                        131
#define IDS_HITS                        132
#define IDS_APPLICATION                 134
#define IDS_UPDATETAGSWARNING           135
#define IDS_LANGUAGE                    136
#define IDS_NEEDSPROGRAMRESATART        137
#define IDS_RECOGNISESONG               139
#define IDS_ADDFILES                    140
#define IDS_UPDATELOCALCOLLECTIONS      141
#define IDS_EXIT                        142
#define IDS_SELECTFOLDER                143
#define IDS_UNKNOWN                     144
#define IDS_QUICK                       145
#define IDS_SEARCH                      146
#define IDS_PLAY                        147
#define IDS_ENQUEUE                     148
#define IDS_ADVSEARCH                   149
#define IDS_HISTORY                     150
#define IDS_OPTIONS                     151
#define IDD_IMAGEPREVIEWDLG             152
#define IDS_COLLECTIONS                 152
#define IDC_IMAGEPREVIEW                153
#define IDS_ABOUT                       153
#define IDC_PREVIEWNAME                 154
#define IDS_ALL                         162
#define IDD_COLLECTIONS                 163
#define IDS_AUDIO                       163
#define IDS_VIDEO                       164
#define IDS_SHOWHIDEMINIPLAYER          167
#define IDS_PLAYPAUSE                   168
#define IDS_STOP                        169
#define IDS_NEXT                        170
#define IDS_PREVIOUS                    171
#define IDD_SEARCH                      172
#define IDS_SHUFFLE                     172
#define IDS_LOOP                        173
#define IDD_HISTORY                     174
#define IDS_SHOWMAINWINDOW              174
#define IDS_SHOWMINIPLAYER              175
#define IDD_LVHEADER                    176
#define IDS_EXITAPPLICATION             176
#define IDD_TVHEADER                    177
#define IDS_RESULTFOUND                 177
#define IDS_RESULTSFOUND                178
#define IDS_PLSENTERMINCHARS            179
#define IDS_MEDIAIDLE                   180
#define IDS_NETWORKIDLE                 181
#define IDS_SCANNINGFILES               183
#define IDS_FILE                        184
#define IDS_DOWNLOADING                 185
#define IDS_AUTOCONTINUE                186
#define IDS_SHOWVISUALIZATIONS          187
#define IDS_RANDOMIZELIST               188
#define IDS_LOADLIST                    189
#define IDS_SAVELIST                    190
#define IDS_CLEARLIST                   191
#define IDS_VARIOUS                     192
#define IDS_DAYSBETWEENCHECK            193
#define IDS_PROPERTIES                  195
#define IDS_POOR                        197
#define IDS_BAD                         197
#define IDS_NEUTRAL                     198
#define IDS_GOOD                        199
#define IDS_VERYGOOD                    200
#define IDD_PPTRACKTAGS                 201
#define IDD_PPTRACKS                    201
#define IDS_OUTSTANDING                 201
#define IDS_OPENCONTAININGFOLDER        202
#define IDD_PPOPTIONSMAIN               203
#define IDS_COPYTO                      203
#define IDS_COPYPATH                    204
#define IDD_PPVARIOUS                   205
#define IDS_RENAMER                     205
#define IDD_PPARTISTSMAIN               206
#define IDD_PPARTISTS                   206
#define IDS_DELETE                      206
#define IDS_DOWNLOADLYRICS              207
#define IDD_PPPICTURE                   208
#define IDS_DELETEOPERATIONTEXT         208
#define IDD_PPINFO                      209
#define IDS_DELETEOPERATION             209
#define IDD_PPALBUMS                    210
#define IDS_WARNING                     210
#define IDS_SIMPLESEARCHTITLE           211
#define IDS_ALLTIME                     212
#define IDI_INFO                        213
#define IDI_INFO16                      213
#define IDI_ICON1                       214
#define IDS_LYRICSAVAILABLE             214
#define IDD_PPMULTIPLETRACKS            215
#define IDS_SPECIALINFOTITLE            215
#define IDS_COMMENTSAVAILABLE           216
#define IDS_PERSONALAVAILABLE           217
#define IDS_TRACKS                      219
#define IDS_ALBUMREVIEW                 221
#define IDS_OPENPICTURE                 223
#define IDS_EDITPICTURE                 224
#define IDS_SAVEPICTURE                 225
#define IDS_SAVETEXT                    226
#define IDB_BITMAP7                     227
#define IDS_OPERATIONFAILED             227
#define IDS_LYRICS                      228
#define IDS_SPECIALINFOPP               229
#define IDB_BITMAP2                     230
#define IDS_POPULAR                     230
#define IDD_PPBESTWORSE                 231
#define IDS_INFONOTFOUND                231
#define IDD_PPRATINGSEARCH              231
#define IDD_PROPPAGE_SMALL              232
#define IDS_COMMENTS                    232
#define IDD_DIALOG1                     233
#define IDS_PERSONAL                    233
#define IDS_SPECIALINFO                 234
#define IDS_ARTISTBIONOTFOUND           235
#define IDS_ARTISTBIO                   236
#define IDS_SIMPLESEARCH                237
#define IDS_FULLTEXTTITLE               238
#define IDS_LATESTADDITIONSTITLE        239
#define IDS_FILETYPEFILTER              240
#define IDS_LATESTADDITIONS             241
#define IDS_SINCE                       242
#define IDS_RATINGTEXT                  243
#define IDS_POPULARTEXT                 244
#define IDB_BITMAP4                     245
#define IDS_FULLTEXTTEXT                245
#define IDD_INFOQUERY                   246
#define IDS_INFORMATIONTYPE             246
#define IDD_DIALOG2                     247
#define IDS_PLEASEWAIT                  247
#define IDD_PPINTERNETOPTIONS           248
#define IDS_BY                          248
#define IDD_PPPLAYEROPTIONS             249
#define IDS_DISABLELYRICSCONF           250
#define IDD_PPFULLTEXT                  251
#define IDS_DISABLELYRICSCONFTITLE      251
#define IDI_TSERROR                     252
#define IDS_EMPTYCOLLECTIONTEXT         252
#define IDI_TSERROR16                   252
#define IDI_ARTISTS_ICON                253
#define IDS_YES_S                       253
#define IDI_ICON2                       254
#define IDS_NO_S                        254
#define IDD_DIALOG3                     255
#define IDS_EMPTYCOLLECTION_TITLE       255
#define IDI_2STARS                      256
#define IDS_YEARS                       256
#define IDI_3STARS                      257
#define IDS_MONTHS                      257
#define IDS_DAYS                        258
#define IDI_ICON6                       259
#define IDS_365DAYS                     259
#define IDS_30DAYS                      260
#define IDS_10DAYS                      261
#define IDD_PPMUSICBROWSEROPTIONS       262
#define IDS_24HOURS                     262
#define IDD_PPTAGGING                   263
#define IDS_TRACKPLAYED                 263
#define IDS_TRACKCLICK                  264
#define IDS_TOP10                       265
#define IDD_EMPTYDB                     266
#define IDS_TOP100                      266
#define IDD_MESSAGE                     266
#define IDD_LIST_TOOLTIP                267
#define IDS_TOPOTHER                    267
#define IDS_RECORDEDHISTORY             271
#define IDS_TOPSONGS                    272
#define IDS_TOPARTISTS                  273
#define IDS_YEAR                        274
#define IDS_MONTH                       275
#define IDS_DAY                         276
#define IDS_UNTILL                      277
#define IDS_UNTIL                       277
#define IDS_NOTENOUGHDATA               278
#define IDS_TIMEINTERVAL                279
#define IDS_INFOWILLBEWRITTEN           280
#define IDS_TIMESLIDER                  281
#define IDS_INFOWILLNOTBEWRITTEN        282
#define IDS_ACTIVE                      283
#define IDS_TEXTFILTERS                 284
#define IDS_TITLE                       285
#define IDS_ARTIST                      286
#define IDS_EXPORTFINISHED              287
#define IDS_DATEFILTER                  288
#define IDS_NORMAL                      289
#define IDS_SHOWNUMITEMS                290
#define IDS_EXTRAINFO                   291
#define IDS_ITEMGROUPING                292
#define IDS_UPDATE                      293
#define IDS_REMOVE                      294
#define IDS_ADDCOLLECTION               295
#define IDS_NAME                        296
#define IDS_ENABLED                     297
#define IDS_MINNUMOFTRACKS              298
#define IDS_MAINTAGS                    299
#define IDS_EXTRATAGS                   300
#define IDS_INTERNETOPTIONS             301
#define IDS_IMPERSONATEBROWSER          302
#define IDS_USEDEFAULTPROXY             303
#define IDS_AUTOMATEDDOWNLOADER         304
#define IDS_SPECIALTAGSSUPPORT          309
#define IDS_AUTOPLAY                    310
#define IDS_REMEMBERLASTTRACK           311
#define IDS_REMEMBERTIME                312
#define IDS_PLAYCONTROL                 313
#define IDS_STARTUP                     314
#define IDS_GENERAL                     315
#define IDS_GLOBALHOTKEYS               316
#define IDS_PICTURE                     317
#define IDS_MINIMIZETOTRAY              318
#define IDS_MINIPLAYER                  319
#define IDS_SHOWALWAYS                  320
#define IDS_AUTOMATIC                   321
#define IDS_MANUALLY                    322
#define IDS_NEVERSHOW                   323
#define IDS_LISTVIEW                    324
#define IDS_SHOWNEWSIGN                 325
#define IDS_ACCEPT                      326
#define IDS_RETRY_S                     327
#define IDS_REFUSE                      328
#define IDS_ACCEPTALL                   329
#define IDS_DONTSHOWAGAIN               330
#define IDS_INFOCHECK                   331
#define IDS_MAINOPTIONS                 332
#define IDS_TREEVIEW                    333
#define IDS_INFORMATIONRETRIEVAL        334
#define IDS_MEDIAPLAYER                 335
#define IDS_TAGGING                     336
#define IDS_MULTIPLETRACKPROPERTIES     340
#define IDS_BIOGRAPHY                   342
#define IDS_REVIEW                      343
#define IDS_IMPORTDATADROMFILE          344
#define IDS_WRITEORPASTETEXT            346
#define IDS_DELETEPICTURE               347
#define IDS_PASTEPICTURE                348
#define IDS_PICTUREDIMENSIONS           349
#define IDS_UPDATEAVAILABLE             350
#define IDS_UPDATENOTAVAILABLE          351
#define IDD_QUIZ                        351
#define IDS_CHECKFORUPDATES             352
#define IDS_GAMES                       353
#define IDS_UPDATECHECKFAILED           354
#define IDD_INPUTBOX                    354
#define IDS_NOPICTUREINCLIPBOARD        355
#define IDS_COLLECTIONLIST              356
#define IDS_START                       358
#define IDS_RESULTS                     359
#define IDS_CORRECTANSWERS              360
#define IDS_WRONGANSWERS                361
#define IDS_SCORE                       362
#define IDS_SUBMITRESULTS               363
#define IDD_PPDETAILEDSEARCH            363
#define IDS_CURRENT                     364
#define IDS_BEST                        365
#define IDS_RENAME                      366
#define IDR_DEFAULTEXPORTSTYLE          366
#define IDS_PLEASEENTERANEWNAME         367
#define IDD_DRIVES                      367
#define IDS_TOTALSCORE                  368
#define IDD_VISVIEW                     368
#define IDS_QUESTION                    369
#define IDI_STOP24                      369
#define IDS_BESTSCORE                   370
#define IDI_NEXT24                      370
#define IDS_CORRECT                     371
#define IDI_PAUSE24                     371
#define IDS_MISTAKE                     372
#define IDI_PLAY24                      372
#define IDS_MUSICQUIZ                   373
#define IDI_PREVIOUS24                  373
#define IDS_ADDING                      374
#define IDI_SEARCH32                    374
#define IDS_COPYTEXT                    375
#define IDS_DETAILEDSEARCHTITLE         376
#define IDI_ENQUEUE32                   376
#define IDS_COLLECTION                  377
#define IDI_HISTORY32                   377
#define IDI_HISTORY16                   377
#define IDS_LOCALFOLDER                 378
#define IDI_OPTIONS32                   378
#define IDS_NETFOLDER                   379
#define IDI_COLLECTIONS32               379
#define IDI_COLLECTIONS16               379
#define IDS_MEDIA                       380
#define IDI_GAMES32                     380
#define IDI_GAMES16                     380
#define IDS_AUDIOCD                     381
#define IDI_ABOUT32                     381
#define IDS_EXTERNALCOLLECTION          382
#define IDS_AUTOUPDDB                   383
#define IDS_COLLECTIONUPDATESTARTED     385
#define IDS_COLLECTIONUPDATEFINISHED    386
#define IDS_REMOVINGFILES               387
#define IDD_SERIALIZETRACKS             387
#define IDS_FILESREMOVED                388
#define IDS_FILESADDED                  389
#define IDS_SHOWHISTORY                 390
#define IDS_CANTLOCATEFILE              391
#define IDS_VIEWEXPORT                  392
#define IDS_PLAYLISTISEMPTY             393
#define IDS_USEMULTIMEDIAHOTKEYS        394
#define IDS_CLIPBOARD                   395
#define IDS_FOLDER                      396
#define IDS_COLLECTION_EXIST            397
#define IDS_DOYOUWANTTOCONTINUE         398
#define IDS_COLLECTIONWASNOTACCESIBLE   399
#define IDS_COLLECTIONISNOTREADY        400
#define IDS_TRACKREMOVEDFROMCOLLECTION  401
#define IDS_REMOVABLE                   402
#define IDS_NOTENOUGHTRACKSTOPLAYTHEQUIZ 403
#define IDS_SHOWALLTRACKS               404
#define IDS_SHOWTRACK                   405
#define IDS_DOWNLOADFREEDBQUERY         406
#define IDS_CDDVDDRIVEISEMPTY           407
#define IDS_SELECTDRIVE                 408
#define IDS_SELECTDRIVEDET              409
#define IDS_GOONLINEQUESTION            410
#define IDS_WORKING                     411
#define IDS_TOTAL                       413
#define IDS_SERVICES                    415
#define IDS_VIRTUALTRACKS               416
#define IDS_ITEMALREADYEXISTS           417
#define IDS_EMPTY                       418
#define IDS_READY                       419
#define IDS_IMPORTVIRTUALTRACKS         420
#define IDS_EXPORTVIRTUALTRACKS         421
#define IDS_IMPORTVIRTUALTRACKSINFO     422
#define IDS_EXPORTVIRTUALTRACKSINFO     423
#define IDS_IMPORT                      424
#define IDS_ADDVIRTUALTRACK             425
#define IDS_EXPORT                      426
#define IDS_INSERTLIST                  427
#define IDI_WINDOW16                    427
#define IDI_OPTIONS16                   428
#define IDS_AUTOCONTINUEMODE            429
#define IDS_INSERTRANDOMTRACKS          430
#define IDS_REMOVEOTHERS                431
#define IDD_PPCOLORS                    431
#define IDS_VISUALIZATIONSVIDEO         432
#define IDS_MUSICBROWSER                434
#define IDI_ICON5                       434
#define IDS_MODE                        435
#define IDS_SORT                        436
#define IDI_ICON3                       436
#define IDS_FILTER                      437
#define IDI_ADD16                       437
#define IDS_PLAYLIST                    438
#define IDS_TRACKLIST                   439
#define IDS_BROWSER                     440
#define IDS_SUCCESS                     441
#define IDI_ICON8                       441
#define IDS_PROVIDER                    442
#define IDI_REFRESH16                   442
#define IDS_FAILURE                     443
#define IDS_VOLUME                      444
#define IDS_AUTO                        445
#define IDS_SYNCWITHPLAYER              446
#define IDS_NEW                         447
#define IDS_MESSENGERNOWPLAYING         448
#define IDI_FORWARD16                   448
#define IDS_TRANSPARENCY                449
#define IDI_BACK16                      449
#define IDS_SKIN                        450
#define IDI_HOME16                      450
#define IDS_LASTFMSCROBBLER             451
#define IDI_INTERNET16                  451
#define IDR_PROGRESSANI                 452
#define IDS_ARTISTPICTURE               452
#define IDS_ALBUMPICTURE                453
#define IDI_CROSSFADE24                 453
#define IDS_SEC                         454
#define IDI_PLAY32                      454
#define IDS_ACTIVATIONDELAY             455
#define IDI_SHINE32                     456
#define IDS_REFUSEALL                   457
#define IDS_CANCEL_S                    458
#define IDS_HELP_S                      459
#define IDI_OVERLAYCHECK                459
#define IDS_PENALTY                     460
#define IDS_BONUS                       461
#define IDI_NOCROSSFADE24               461
#define IDS_GAMEOVER                    462
#define IDI_TOPREST16                   462
#define IDS_TOTALTIME                   463
#define IDI_TOP1016                     463
#define IDS_GAMEINFO                    464
#define IDI_TOP10016                    464
#define IDS_IDONTKNOW                   465
#define IDI_PLAYED16                    465
#define IDS_LEVEL                       466
#define IDI_MOUSECLICK16                466
#define IDS_SELECTGAME                  467
#define IDI_MINUS16                     467
#define IDS_CROSSFADE                   468
#define IDI_AUDIO16                     468
#define IDS_DISABLED                    469
#define IDI_VIDEO16                     469
#define IDS_END                         470
#define IDI_COMMENTS16                  470
#define IDS_BOTH                        471
#define IDI_LYRICS16                    471
#define IDI_PERSONAL16                  472
#define IDS_EXTERNALPLAYER              472
#define IDI_STAREMPTY16                 473
#define IDS_CHANGECASE                  473
#define IDI_STARGOLD16                  474
#define IDS_ALLCAPS                     474
#define IDI_STARBAD16                   475
#define IDS_NOCAPS                      475
#define IDI_VIRTUAL16                   476
#define IDS_PROPERCASE                  476
#define IDI_NEW16                       477
#define IDS_FIRSTCAP                    477
#define IDI_COLLAPSED16                 478
#define IDS_ADVANCED                    478
#define IDI_EXPLANDED16                 479
#define IDI_EXPANDED16                  479
#define IDI_REMOVABLE16                 480
#define IDS_APPEARANCE                  480
#define IDI_AUDIOCD16                   481
#define IDS_TOOLTIPS                    481
#define IDI_MEDIA16                     482
#define IDS_BEHAVIOUR                   482
#define IDI_NETFOLDER16                 483
#define IDS_MAXSIZE                     483
#define IDI_LOCALFOLDER16               484
#define IDS_AUTHOR                      484
#define IDI_PLAY16                      485
#define IDS_STATISTICS                  485
#define IDS_DESCRIPTION                 486
#define IDI_FIND16                      487
#define IDS_INFORMATION                 487
#define IDI_COPY16                      488
#define IDS_PAUSE                       488
#define IDI_DELETE16                    489
#define IDS_DOWNLOAD                    489
#define IDI_PROPERTIES16                490
#define IDS_CREATE                      490
#define IDI_PROVIDERS16                 491
#define IDS_UPDATEINFOFROMTAGS          491
#define IDI_PICTURE16                   492
#define IDS_LOCATEALBUM                 492
#define IDI_TEXT16                      493
#define IDS_MOREOPTIONS                 493
#define IDD_PPMINIPLAYER                494
#define IDS_DESCENDING                  494
#define IDD_PPLANGUAGES                 495
#define IDS_VERSION                     496
#define IDD_PPSKINS                     496
#define IDI_EXPAND16                    497
#define IDS_STYLE                       497
#define IDS_CONTROLS                    498
#define IDI_UP16                        499
#define IDS_CLEAR                       499
#define IDI_DOWN16                      500
#define IDS_TAGWRITER                   500
#define IDR_ALBUM                       501
#define IDS_TAGREADER                   501
#define IDS_READDEPTH                   502
#define IDI_STARGOLDHALF16              503
#define IDS_COUNTINGFILES               503
#define IDI_STARBADEMPTY16              504
#define IDS_FILECOULDNOTBEDELETED       504
#define IDS_PROCESSTIME                 505
#define IDI_BUY16                       505
#define IDS_COMMERCIALINFO              506
#define IDS_PURCHASEINFO                506
#define IDI_EQUALIZER_AC16              506
#define IDS_SIMILAR                     507
#define IDI_CROSSFADE16                 507
#define IDS_PREVIEW                     508
#define IDI_CROSSFADE_AC16              508
#define IDS_MOREALBUMS                  509
#define IDI_EQUALIZER16                 509
#define IDS_EQUALIZER                   510
#define IDS_READTAGS                    511
#define IDD_PPGLOBALHOTKEYS             511
#define IDS_WRITETAGS                   512
#define IDD_RENAMER                     512
#define IDS_GETTAGSFROMFILENAME         513
#define IDD_TAGSFROMFILENAME            513
#define IDS_OK                          514
#define IDR_PNG_ARTIST                  514
#define IDS_EMPTYCOLLECTION_DETAIL      515
#define IDD_PPGENERIC                   515
#define IDS_DEBUGGING                   516
#define IDS_FOLDERIMAGES                517
#define IDI_ICON4                       517
#define IDI_TABLATURE16                 517
#define IDS_PATTERN                     518
#define IDS_SKIP                        519
#define IDS_SYMBOLS                     520
#define IDD_LASTFM                      520
#define IDS_SHOW                        521
#define IDD_USERPROGRESS                521
#define IDS_TABLATURES                  522
#define IDD_SIMPLEEDITOR                522
#define IDS_AUTODEBUG                   523
#define IDI_ICON7                       523
#define IDI_SWITCHPANE16                523
#define IDS_USERNAME                    524
#define IDI_ICON9                       524
#define IDI_DECREASEFONT16              524
#define IDS_PASSWORD                    525
#define IDI_ICON10                      525
#define IDI_INCREASEFONT16              525
#define IDS_TSONLINESERVICES            526
#define IDI_ICON11                      526
#define IDI_RESETFONT16                 526
#define IDS_CHECK                       527
#define IDI_ICON12                      527
#define IDI_RESTORE16                   527
#define IDS_DEFAULT                     528
#define IDI_ICON13                      528
#define IDI_MINIMIZE16                  528
#define IDS_DONOTASKAGAIN               529
#define IDI_ICON14                      529
#define IDI_CLOSE16                     529
#define IDS_CONFIRMATION                530
#define IDI_ICON15                      530
#define IDI_MAXIMIZE16                  530
#define IDS_FOCUS                       531
#define IDI_ICON16                      531
#define IDI_CLEAR16                     531
#define IDS_OVER                        532
#define IDD_ADDPANE                     532
#define IDS_HIDE                        533
#define IDI_INSERT16                    533
#define IDS_SHOWONMINIMIZEHIDEONRESTORE 534
#define IDI_ALBUM16                     534
#define IDS_TOGGLE                      535
#define IDI_ICON17                      535
#define IDI_REMOVE16                    535
#define IDS_REMOVEITFROMDATABASE        536
#define IDS_APPLY                       537
#define IDS_STRING118                   538
#define IDS_RELATIVEFONTSIZE            538
#define IDI_ICON18                      538
#define IDI_UNMUTE16                    538
#define IDI_NOMUTE16                    538
#define IDS_KEYENTER                    539
#define IDI_ICON19                      539
#define IDI_MUTE16                      539
#define IDS_KEYBACK                     540
#define IDR_YOUTUBEAPIPAGE              540
#define IDS_KEYINSERT                   541
#define IDS_KEYHOME                     542
#define IDS_KEYNUMPAD                   543
#define IDS_LOOKIN                      544
#define IDS_PERSONALPAGE                545
#define IDS_WEBSITE                     546
#define IDS_FORUM                       547
#define IDS_DONATION                    548
#define IDS_REMOVEUNDERSCORES           549
#define IDS_UPDATING                    550
#define IDS_ALTERNATIVELAYOUT           551
#define IDS_SHOWNUMBERS                 552
#define IDS_SAFEMODE                    553
#define IDS_SHOWINFOICONS               554
#define IDS_FORCECLEARTYPEFONTS         555
#define IDS_MINIMUMCHARACTERS           556
#define IDS_EMAIL                       557
#define IDS_CREATEPREVIEW               558
#define IDS_SYNCWITHSECTIONS            559
#define IDS_SYNCWITHTRACKS              560
#define IDS_ADDPANE                     561
#define IDS_UP                          562
#define IDS_DOWN                        563
#define IDS_LEFT                        564
#define IDS_RIGHT                       565
#define IDS_POSITION                    566
#define IDS_RANDOMIZENEXT               567
#define IDS_VISUALIZATIONS              568
#define IDS_NEWDEFINITION               569
#define IDS_WEB                         570
#define IDS_WEBVIEWER                   571
#define IDS_FORCEONTOP                  572
#define IDS_RESETWINDOWLAYOUT           573
#define IDS_KEYSHIFT                    574
#define IDS_KEYCTRL                     575
#define IDS_KEYALT                      576
#define IDS_INSERTAFTER                 577
#define IDS_DISABLEONMOUSEOVER          578
#define IDS_MUTE                        579
#define IDS_SHOWTOOLTIPONMEDIACHANGED   580
#define IDS_TRAYTOOLTIP                 581
#define IDS_ALBUMARTIST                 582
#define DEFAULTPLAYERACTION             582
#define IDS_DEFAULTPLAYERACTION         582
#define IDS_COMPOSER                    583
#define IDC_LIST1                       1000
#define IDC_LISTVIEW                    1000
#define IDC_LIST                        1000
#define IDC_LISTBOX                     1000
#define IDC_TREEVIEW                    1001
#define IDC_LISTTOPART                  1001
#define IDC_HTMLVIEW                    1002
#define IDC_INFOCONTROL                 1002
#define IDC_LISTTOPTRA                  1002
#define IDC_PLAYLIST                    1002
#define IDC_RESULT                      1002
#define IDC_PLAYER                      1004
#define IDC_PLAYERVIEW                  1004
#define IDC_PLAYERVIEW1                 1004
#define IDC_LISTPLAYER                  1006
#define IDC_PLAYERTB                    1008
#define IDC_PREVIOUS                    1009
#define IDC_ENQUEUE                     1011
#define IDC_SEARCH                      1012
#define IDC_NEXT                        1013
#define IDC_SLIDER                      1014
#define IDC_MEDIAPLAYER                 1015
#define IDC_BUTTON1                     1016
#define IDC_DOWNLOAD                    1016
#define IDC_ASSIGN                      1016
#define IDC_DATEPICKER                  1016
#define IDC_PREV                        1016
#define IDC_YES                         1016
#define IDC_YESBUT                      1016
#define IDC_OPTION1                     1016
#define IDC_APPLY                       1016
#define IDC_ADD                         1016
#define IDC_CREATELNG                   1016
#define IDC_OK                          1016
#define IDC_GETTAGS                     1016
#define IDC_BTN2                        1016
#define IDC_CMD_CHECKLOGIN              1016
#define IDC_CMD_LASTFM                  1016
#define IDC_RESET                       1016
#define IDC_EDT_SIMPLE                  1017
#define IDC_NOBUT                       1017
#define IDC_OPTION2                     1017
#define IDC_ACTIONS                     1017
#define IDC_UPDATELNG                   1017
#define IDC_HELP_S                      1017
#define IDC_BTN1                        1017
#define IDC_CMD_ONLINESERVICES          1017
#define IDC_OPTION3                     1018
#define IDC_HELPLNG                     1018
#define IDC_BTN3                        1018
#define IDC_OPTION4                     1019
#define IDC_DOWNLOADLNG                 1019
#define IDC_LST_SEARCH                  1020
#define IDC_OPENFOLDER                  1020
#define IDC_TAB_SEARCH                  1022
#define IDC_CHK_USEOPTIONS              1023
#define IDC_LST_OPTIONS                 1024
#define IDC_CMD_CHANGE                  1025
#define IDC_TAB                         1026
#define IDC_CMBDATE                     1028
#define IDC_SCRDATE                     1029
#define IDC_MEDIAUSAGE                  1029
#define IDC_LBLDATE                     1030
#define IDC_EDT_ARTIST                  1031
#define IDC_EDT_TRACK                   1032
#define IDC_EDT_ALBUM                   1032
#define IDC_BTN_RESET                   1033
#define IDC_EDT_TITLE                   1033
#define ID_EXIT                         1034
#define IDC_EDT_LOCATION                1034
#define IDC_ENHTREECTRL                 1042
#define IDC_ENHLISTCTRL                 1043
#define IDC_ENHTREECTRL2                1043
#define IDC_TREEPIC                     1045
#define IDC_BROWSER                     1047
#define IDC_STYLE                       1048
#define IDC_FILTER                      1049
#define ID_ADD                          1051
#define ID_UPDATE                       1052
#define IDC_SITE                        1052
#define IDC_THANKS                      1053
#define IDC_SITE2                       1053
#define IDC_FORUM                       1053
#define IDC_TRACKNAME                   1054
#define IDC_LANGPACKS                   1054
#define IDC_ALBUMNAME                   1055
#define IDC_ARTISTNAME                  1056
#define IDC_GENRENAME                   1057
#define IDC_INFO                        1057
#define IDC_YEARNAME                    1058
#define IDC_CHKRO                       1058
#define IDC_YEAR                        1058
#define IDC_HELPLINK                    1058
#define IDC_INFO3                       1058
#define IDC_OPEN                        1059
#define IDC_YEARNAME2                   1059
#define IDC_TRACKNO                     1059
#define IDC_INFO2                       1059
#define IDC_COMMENT                     1059
#define IDC_COLLECTION                  1060
#define IDC_SUBTITLE                    1061
#define IDC_ALBUMARTIST                 1061
#define IDC_EDIT1                       1062
#define IDC_EDTSEARCH                   1062
#define IDC_SEARCHEDT                   1062
#define IDC_MESSAGE                     1062
#define IDC_INFORMATION                 1062
#define IDC_EDTIMPERSONATE              1062
#define IDC_INPUTSTRING                 1062
#define IDC_EDT_AUTOUPDDB               1062
#define IDC_LOCATION                    1062
#define IDC_EDT_DELAY                   1062
#define IDC_EDT_RD_AUTO                 1062
#define IDC_EDT_USER                    1062
#define IDC_EDIT                        1062
#define IDC_CHK_RO                      1063
#define IDC_EDT_RD_MANUAL               1063
#define IDC_EDT_PASS                    1063
#define IDC_GENRENAME3                  1063
#define IDC_COMPOSER                    1063
#define IDC_PPMTWARNING                 1064
#define IDC_PPTINFO                     1065
#define IDC_PPMTINFO                    1065
#define IDC_CMBRATING                   1066
#define IDC_PIC                         1067
#define IDC_TITLE                       1068
#define IDC_TITLE2                      1069
#define IDC_VERSION                     1069
#define IDC_CHK_ENABLETAGGING           1070
#define IDC_CHK_TAGLYRICS               1071
#define IDC_CHK_TAGPERSONAL             1072
#define IDC_CHK_TAGLYRICS3              1073
#define IDC_CHK_TAGRATING               1073
#define IDC_CMBGROUPING                 1074
#define IDC_CHKSHOWNUMITEMS             1075
#define IDC_CHKSHOWYEAR                 1076
#define IDC_CHK_SHOWVISUALIZATIONS      1077
#define IDC_CMBNUMDAYS                  1077
#define IDC_CHK_TAGPERSONAL3            1078
#define IDC_CHK_LOOP                    1078
#define IDC_CHK_SHUFFLE                 1079
#define IDC_HK_PLAY                     1080
#define IDC_HOTKEY2                     1081
#define IDC_HK_STOP                     1081
#define IDC_LISTCTRLHDR                 1081
#define IDC_HOTKEY3                     1082
#define IDC_HK_PREVIOUS                 1082
#define IDC_RADIO1                      1082
#define IDC_RDALL                       1082
#define IDC_RD3STAR                     1082
#define IDC_RD_DEFAULT                  1082
#define IDC_RD_LEFT                     1082
#define IDC_HOTKEY4                     1083
#define IDC_HK_NEXT2                    1083
#define IDC_HK_NEXT                     1083
#define IDC_RADIO2                      1083
#define IDC_RDAUDIO                     1083
#define IDC_RD2STAR                     1083
#define IDC_RD_RIGHT                    1083
#define IDC_RADIO3                      1084
#define IDC_RDVIDEO                     1084
#define IDC_RD3STAR3                    1084
#define IDC_RD1STAR                     1084
#define IDC_SHOWAUTO                    1084
#define IDC_HK_MINILAYER                1084
#define IDC_HK_MINIPLAYER               1084
#define IDC_RD_UP                       1084
#define IDC_CHECK1                      1085
#define IDC_ENABLED                     1085
#define IDC_RD0STAR                     1085
#define IDC_DONT_ASK_AGAIN              1085
#define IDC_DONT_SHOW_AGAIN             1085
#define IDC_CHK_AUTO_DL                 1085
#define IDC_CHK_AUTOPLAY                1085
#define IDC_CHK_ENABLEGROUPING          1085
#define IDC_SHOWALWAYS                  1085
#define IDC_SHOWALLTRACKS               1085
#define IDC_CHK_ALBUM                   1085
#define IDC_CHK_WRITETAGS               1085
#define IDC_CHK_ARTISTBIO               1085
#define IDC_CHK_DONOTASKAGAIN           1085
#define IDC_CHECKBOX                    1085
#define IDC_CHK_OVER                    1085
#define IDC_RD_DOWN                     1085
#define IDC_HK_TOOLTIP                  1085
#define IDC_CHK_AUTO_DL2                1086
#define IDC_CHK_PREFERNC                1086
#define IDC_CHK_REMTRACK                1086
#define IDC_SHOWNEVER                   1086
#define IDC_CHK_ARTIST                  1086
#define IDC_CHK_ALBUMREVIEW             1086
#define IDC_CHK_AUTOMATIC               1086
#define IDC_HK_QUICKSEARCH              1086
#define IDC_CHK_REMTIME                 1087
#define IDC_SHOWMANUALLY                1087
#define IDC_CHK_GENRE                   1087
#define IDC_CHK_TRACKCOMMENTS           1087
#define IDC_CHK_AUTOMATIC2              1087
#define IDC_CHK_FORCEONTOP              1087
#define IDC_CHK_YEAR                    1088
#define IDC_CHK_TRACKLYRICS             1088
#define IDC_SEARCHLABEL                 1089
#define IDC_CHK_COMMENT                 1089
#define IDC_CHK_TRACKPERSONAL           1089
#define IDC_CHK_MIN2TRAY                1090
#define IDC_CHK_ARTISTIMAGE             1090
#define IDC_CHK_AUTOUPDDB               1091
#define IDC_CHK_ARTISTIMAGE2            1091
#define IDC_CHK_ALBUMIMAGE              1091
#define IDC_ANIMATE1                    1092
#define IDC_ANIMATE                     1092
#define IDC_CHK_LASTFMSCROBBLING        1092
#define IDC_ANIMATION                   1093
#define IDC_CHK_MSNNOWPLAYING           1093
#define IDC_CHK_USEAMART                1094
#define IDC_CHK_DLARTBIO                1094
#define IDC_CHK_TSONLINESERVICES        1094
#define IDC_CHK_USEAMALB                1095
#define IDC_CHK_DLALBREV                1095
#define IDC_CHK_USENC                   1096
#define IDC_CHK_DLARTPIC                1096
#define IDC_CHK_USEGLYRICS              1097
#define IDC_CHK_DLALBPIC                1097
#define IDC_CHECK2                      1098
#define IDC_IMPERSONATE                 1098
#define IDC_CHK_USEMULTIMEDIAHOTKEYS    1098
#define IDC_CHK_DLTRALYR                1098
#define IDC_CHK_CHECKFORUPDATES         1098
#define IDC_CHK_SHOWTOOLTIPS            1098
#define IDC_CHK_USEFOLDERIMAGES         1098
#define IDC_CHK_REMOVEUNDERSCORES       1098
#define IDC_CHK_SAFEMODE                1098
#define IDC_CHECK3                      1099
#define IDC_USEDEFAULTPROXY             1099
#define IDC_CHK_CFENABLED               1099
#define IDC_CHK_SHOWMOREINFO            1099
#define IDC_CHK_DEBUGGING               1099
#define IDC_TEXT                        1100
#define IDC_CHK_DEBUGGING2              1100
#define IDC_CHK_AUTODEBUG               1100
#define IDC_CHK_FORCECLEARTYPEFONTS     1100
#define IDC_RDLYRICS                    1101
#define IDC_CHK_SHOWTOOLTIPSONMEDIACHANGED 1101
#define IDC_RD_COMMENTS                 1102
#define IDC_RDCOMMENTS                  1102
#define IDC_RDPERSONAL                  1103
#define IDC_PROGRESS1                   1104
#define IDC_PROGRESS                    1104
#define IDC_NETUSAGE                    1106
#define IDC_NAME                        1106
#define IDC_EDTNUMDAYS                  1107
#define IDC_CHK_AUTOCONTINUE            1109
#define IDC_CHECKUPDATES                1110
#define IDC_CMB_PLAYCONTROL             1113
#define IDC_CMB_DEFAULTPLAYERACTION     1114
#define IDC_ARTIST                      1115
#define IDC_RATING                      1116
#define IDC_INDEX                       1117
#define IDC_FTGROUP                     1118
#define IDC_SINCE                       1119
#define IDC_ITGROUP                     1120
#define IDC_DATEFILTER                  1121
#define IDC_TIMEINTERVAL                1122
#define IDC_PAST                        1123
#define IDC_TIMESLIDER                  1124
#define IDC_NOW                         1125
#define IDC_ACTIVE                      1126
#define IDC_TEXTFILTERS                 1127
#define IDC_GRPITEMGROUPING             1128
#define IDC_GRPEXTRAINFO                1129
#define IDC_MINNUMTRACKS                1130
#define IDC_INTERNETOPTIONS             1131
#define IDC_GRPAUTOMATEDDOWNLOADER      1132
#define IDC_ST_TRACKNO                  1133
#define IDC_ST_ALBUM                    1134
#define IDC_ST_ARTIST                   1135
#define IDC_ST_GENRE                    1136
#define IDC_ST_YEAR                     1137
#define IDC_GR_MAINTAGS                 1138
#define IDC_ST_LOCATION                 1138
#define IDC_GR_EXTRATAGS                1139
#define IDC_ST_TITLE                    1140
#define IDC_GR_SPECIALTAGSSUPPORT       1141
#define IDC_ST_COLLECTION               1141
#define IDC_GR_STARTUP                  1142
#define IDC_ST_ALBUMARTIST              1142
#define IDC_GR_GENERAL                  1143
#define IDC_ST_COMPOSER                 1143
#define IDC_ST_PLAYCONTROL              1144
#define IDC_GR_GLOBALHOTKEYS            1145
#define IDC_ST_DEFAULTPLAYERACTION      1145
#define IDC_ST_PLAY                     1146
#define IDC_ST_STOP                     1147
#define IDC_ST_PREVIOUS                 1148
#define IDC_ST_NEXT                     1149
#define IDC_GR_PICTURE                  1150
#define IDC_ST_MINIPLAYER               1150
#define IDC_ST_NEWSIGN                  1151
#define IDC_ST_TOOLTIP                  1151
#define IDC_GR_MINIPLAYER               1152
#define IDC_GRP_BEHAVIOUR               1152
#define IDC_GR_LISTVIEW                 1153
#define IDC_ST_COMMENT                  1154
#define IDC_ST_RATING                   1155
#define IDC_CMBLANGUAGES                1157
#define IDC_GUILANGUAGE                 1158
#define IDC_NEEDSPROGRAMRESTART         1159
#define IDC_GR_APPLICATION              1160
#define IDC_COLLECTIONS_INFO1           1161
#define IDC_CMBSKINS                    1161
#define IDC_COLLECTIONS_INFO2           1162
#define IDC_COLLECTIONLIST              1163
#define IDC_QUESTION                    1165
#define IDC_CAPTION                     1166
#define IDC_IDONTKNOW                   1172
#define IDC_OPTION5                     1172
#define IDC_TOTALSCORE                  1173
#define IDC_TOTALSCORENUM               1174
#define IDC_QUESTIONNO                  1175
#define IDC_QUESTIONNONUM               1176
#define IDC_QUESTIONSCORE               1177
#define IDC_QUESTIONNONUM2              1178
#define IDC_QUESTIONSCORENUM            1178
#define IDC_BESTSCORE                   1179
#define IDC_BESTSCORENUM                1180
#define IDC_SUBMIT                      1182
#define IDC_INSTRUCTIONS                1183
#define IDC_LANGUAGEPACKINFO            1186
#define IDC_HIDDENINFO                  1188
#define IDC_LANGINFO                    1188
#define IDC_GR_LOCATION                 1189
#define IDC_TRACKLIST                   1190
#define IDC_IMG                         1191
#define IDC_HEADER                      1192
#define IDC_SKIN                        1195
#define IDC_ST_ACTIVATIONDELAY          1196
#define IDC_ST_DEFPROVIDER              1197
#define IDC_CMB_ARTPIC                  1198
#define IDC_CMB_ARTBIO                  1199
#define IDC_CMB_ALBPIC                  1200
#define IDC_ACCEPT                      1200
#define IDC_CMB_ALBREV                  1201
#define IDC_GR_CROSSFADE                1201
#define IDC_CMB_TRALYR                  1202
#define IDC_ST_SEC                      1203
#define IDC_ST_CFSTART                  1203
#define IDC_ST_CFSTART2                 1204
#define IDC_ST_CFEND                    1204
#define IDC_SLDSTART                    1205
#define IDC_SLDEND                      1206
#define IDC_SLDTRANSPARENCY             1206
#define IDC_TRANSPARENCY                1207
#define IDC_GRP_SHOW                    1208
#define IDC_GRP_APPEARANCE              1209
#define IDC_SLD_MAXSIZE                 1210
#define IDC_MOREINFO                    1210
#define IDC_MAXSIZE                     1211
#define IDC_GRP_SELECT                  1213
#define IDC_GRP_INVOLVE                 1214
#define IDC_SKININFO                    1215
#define IDC_DOWNLOADSKIN                1216
#define IDC_CREATESKIN                  1217
#define IDC_DOWNLOADSKIN2               1217
#define IDC_UPDATESKIN                  1218
#define IDC_HELPSKIN                    1219
#define IDC_SCREENSHOT                  1220
#define IDC_CREATEPREVIEW               1221
#define IDC_GRP_ACTIONS                 1225
#define IDC_GRP_ACTIVE                  1226
#define IDC_GRP_OPTIONS                 1227
#define IDC_OLDTREEVIEW                 1228
#define IDC_ST_RD_AUTO                  1232
#define IDC_ST_RD_MANUAL                1233
#define IDC_SLD_RD_AUTO                 1234
#define IDC_SLD_RD_MANUAL               1235
#define IDC_GR_TAGWRITER                1236
#define IDC_GR_TAGREADER                1237
#define IDC_CMB_VISIBILITY              1243
#define IDC_EDT_PREVIEW                 1250
#define IDC_ST_SYMBOLS                  1252
#define IDC_ST_CASING                   1253
#define IDC_ST_FILENAME                 1254
#define IDC_ST_PATTERN                  1255
#define IDC_ST_PREVIEW                  1256
#define IDC_RENAME                      1257
#define IDC_SKIP                        1258
#define IDC_ALL                         1259
#define IDC_CANCEL                      1260
#define IDC_CMB_CASING                  1262
#define IDC_EDT_FILENAME                1264
#define IDC_CMB_PATTERN                 1265
#define IDC_LST_TAGS                    1268
#define IDC_ST_TRACKS                   1269
#define IDC_BTN_AUTO                    1270
#define IDC_SLD_RATING                  1271
#define IDC_USER                        1274
#define IDC_PASS                        1275
#define IDC_LINK                        1277
#define IDC_RATINGDESC                  1279
#define IDC_SAVE                        1280
#define IDC_DEBUG                       1281
#define IDC_LST_READ                    1286
#define IDC_LST_READ2                   1287
#define IDC_LST_WRITE                   1287
#define IDC_GRP_POSITION                1287
#define IDC_LST_PANES                   1289
#define IDC_ST_QUICKSEARCH              1291
#define IDI_WARN                        32515
#define IDI_WARN16                      32515
#define ID_PLAYER_PLAY                  32776
#define ID_PLAYER_ENQUEUE               32777
#define ID_FRM_FIND                     32778
#define ID_FRM_OPTIONS                  32780
#define ID_FRM_COLLECTIONS              32782
#define ID_FRM_ABOUT                    32783
#define ID_FRM_HISTORY                  32784
#define ID_FRM_COLLECTION               32785
#define ID_TBPREVIOUS                   32787
#define ID_TBPLAY                       32788
#define ID_TBPAUSE                      32789
#define ID_TBSTOP                       32790
#define ID_TBNEXT                       32791
#define ID_ADD_FOLDER                   32792
#define IDD_ADD_NETFOLDER               32793
#define ID_ADD_MEDIA                    32794
#define ID_ADDCOLLECTION                32795
#define IDD_REFRESH_QUICK               32796
#define IDD_REFRESH_2SIDE               32797
#define IDD_REFRESH_REREAD              32798
#define ID_REFRESH_BACKGROUND           32799
#define ID_POPUP_FILEOPERATIONS         32803
#define ID_FILEOPERATIONS_COPY          32804
#define ID_FILEOPERATIONS_MOVETO        32805
#define ID_FILEOPERATIONS_COPYPATH      32806
#define ID_FILEOPERATIONS_DELETE        32807
#define ID_POPUP_NAMETOTAGS             32809
#define ID_POPUP_PROPERTIES32810        32810
#define ID_RATING_EXCELLENT             32812
#define ID_RATING_VERYGOOD              32813
#define ID_RATING_NICE                  32814
#define ID_RATING_NEUTRAL               32815
#define ID_RATING_BAD                   32816
#define ID_BUTTON32852                  32852
#define ID_MAINLISTNORMAL_DLLYRICS      32856
#define ID_RATINGS_OUTSTANDING          32857
#define ID_RATINGS_EXCELLENT            32858
#define ID_RATINGS_NICE                 32859
#define ID_RATINGS_OK                   32860
#define ID_RATINGS_BAD                  32861
#define ID_RATINGS_5                    32862
#define ID_RATINGS_4                    32863
#define ID_RATINGS_3                    32864
#define ID_RATINGS_2                    32865
#define ID_RATINGS_1                    32866
#define ID_MAINLISTNORMrating_AL5       32867
#define ID_MAINLISTNORMrating_AL1       32868
#define ID_MAINLISTNORMrating_AL2       32869
#define ID_MAINLISTNORMrating_AL3       32870
#define ID_MAINLISTNORMrating_AL4       32871
#define ID_MAINLISTNORMAL_FIL_VID       32883
#define ID_MAINLISTNORMAL_PL_SHUFFLE    32883
#define ID_MAINLISTNORMAL_VISUALIZATIONS_DOCKED 32887
#define ID_MAINLISTNORMAL_OPTIONS       32892
#define ID_MAINLISTNORMAL_EXITAPP       32893

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        541
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1292
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
